theme: jekyll-theme-merlot
```It is a twitter bot which automatically like posts from different hashtags and username. 1st you need to add your API keys into the keys.py file. then you need certain python version like python2,python3.4,python3.6 so that to install tweepy install tweepy using ------>> pip install tweepy```
